### ISSUE TITLE
Copy link Button breaking on Tribes

### ISSUE THREAD

**Issue by gouravmpk** [stakwork/sphinx-tribes-frontend#54] opened 2024-01-28 17:57 UTC
**Describe the bug**
<img width="1104" alt="image" src="https://github.com/stakwork/sphinx-tribes-frontend/assets/20900042/6d1d8220-e6e1-4b38-b04a-4811a90f0029">

**To Reproduce**
1. Go to 'https://community.sphinx.chat/t/bountyhuntersjobboard'
2. Click on any tribe
3. See error

**Expected behavior**
 button in correct format

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a screenshot or video in my PR

**Comment by ecurrencyhodler** [comment] 2024-01-28 18:04
Gourav is this a duplicate of #53 ?

**Comment by gouravmpk** [comment] 2024-01-28 18:06
> Gourav is this a duplicate of #53 ?

ohh I didnt noticed 
that someone already created the issue for this

**Closed** 2024-01-28 18:07 UTC
Labels: bug, Bounties

**Comment by ecurrencyhodler** [comment] 2024-01-28 18:09
np!
