### ISSUE TITLE
fix the issue of Pay until date box hover effect and without select the pay until box we are able to select date on the 'Send Tip' popup.

### ISSUE THREAD

**Issue by MahtabBukhari** [stakwork/sphinx-tribes-frontend#98] opened 2024-01-31 03:07 UTC
**Describe the bug**
When we go to the people page, select a people card, and click on the 'Send Tip' button, a popup opens. In this popup, when we hover over the unselected 'Pay Until' date box, it shows the 'Select Date' card.

https://www.loom.com/share/1f408c2e20624ea288f28dadfd3aeb69?sid=0aa02b60-d274-4960-880e-ffc2b44f5416

**To Reproduce**
1. Go to 'People page'
2. select a 'people card'
3. click on 'Send Tip'
4. hover over pay until date box with out selecting Pay until check box
5. see the bug

**Expected behavior**
In Send Tip popup, when we hover over the unselected 'Pay Until' date box, it shows the 'Select Date' card. It should not be displayed until we select the 'Pay Until' checkbox.

**Desktop (please complete the following information):**
 - Browser [chrome]

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a screenshot or video in my PR

**Comment by MahtabBukhari** [comment] 2024-01-31 03:07
@ecurrencyhodler kindly also see this one

**Comment by ecurrencyhodler** [comment] 2024-01-31 05:40
Thanks for submitting this issue. This is a duplicate of https://github.com/stakwork/sphinx-tribes-frontend/issues/80

**Closed by ecurrencyhodler** 2024-01-31 05:40 UTC
Labels: bug, Bounties
